# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# apply AWS nifi security group rules for multi-interface systems
---
- name: NIFI OVERLAY | discovering nifi instances
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Tenant": "{{ tenant }}"
      "tag:Project": "{{ project }}"
      "tag:Domain": "{{ domain }}"
      "tag:Application": 'nifi'
      # "tag:Cluster": "{{ cluster | default ('a') }}"
      "tag:Dataflow": "{{ dataflow | default('none') }}"
  register: all_nifi_nodes
  when:
    - cloud == 'aws'
    - "'nifi' in groups | default([])"
  
- block:

  # construct list of all interfaces attached to nifi nodes
  - set_fact:
      nifi_interfaces: "{{ all_nifi_nodes.instances | map(attribute='network_interfaces') | list }}"

  # apply internal SSH rule
  - name: NIFI OVERLAY | applying ssh security rules to interface 0
    ec2_eni:
      region: "{{ region }}"
      eni_id: "{{ item.network_interface_id }}"
      security_groups:
        - "{{ sg_ssh_private.security_groups.0.group_id }}"
    with_items: "{{ nifi_interfaces }}"
    when: item.attachment.device_index == 0
  
  # apply nifi rules
  - name: NIFI OVERLAY | applying nifi security rules to interface 1
    ec2_eni:
      region: "{{ region }}"
      eni_id: "{{ item.network_interface_id }}"
      security_groups:
        - "{{ sg_nifi_external.group_id }}"
    with_items: "{{ nifi_interfaces }}"
    when: item.attachment.device_index == 1
    
  when:
    - "'nifi' in groups | default([])"
    - groups.nifi | length > 0
