# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# OS tasks that occur post-boot and pre-appplication installation
---
# shell limits
- import_tasks: limits.yml
# kernel tuning
- import_tasks: kernel.yml
# vm tuning
- import_tasks: vm.yml

# https://nifi.apache.org/docs.html
- name: NIFI OVERLAY | increasing the number of TCP ports available
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: "10000 65000"
    state: present
  become: yes

# this isn't supported on CentOS/RHEL
# - name: NIFI OVERLAY | adjusting TIMED_WAIT state when closed
#   sysctl:
#     name: net.ipv4.netfilter.ip_conntrack_tcp_timeout_time_wait
#     value: 1
#     state: present
#     reload: yes
#   become: yes

- name: NIFI OVERLAY | turning off vm swap
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
    reload: yes
  become: yes
    